[package]
name = "Launchpad"
version = "1.3.1"
published-at = "0xfce606f93791b53b2edddc55abd7c3bc7b1060f7680e9b93c6d5e34796f329a4"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# mainnet-1.3.1
rev = "a2af559f9ea21e09ca7e377e3b477fc2b5239fc7"

[dependencies.Originmate]
git = "https://github.com/Origin-Byte/originmate.git"
# mainnet-1.3.1
rev = "8d5fc07db61447e8dd3e699556aaf9cea1ebf463"

[dependencies.Kiosk]
local = "./../kiosk"

[dependencies.Pseudorandom]
local = "./../pseudorandom"

[dependencies.Utils]
local = "./../utils"

[addresses]
ob_launchpad = "0xfce606f93791b53b2edddc55abd7c3bc7b1060f7680e9b93c6d5e34796f329a4"
